from __future__ import annotations

from tokentoll.core.models import (
    CostEstimate,
    DiffReport,
    ScanReport,
    Verdict,
    VerdictLevel,
)

_VERDICT_BANNER = {
    VerdictLevel.PASS: "PASS",
    VerdictLevel.WARN: "WARN",
    VerdictLevel.FAIL: "FAIL",
}

_VERDICT_REQUIRED_ACTION = {
    VerdictLevel.FAIL: (
        "Required action: revert the regression, raise the threshold in "
        "`.tokentoll.yml`, or add an exemption."
    ),
    VerdictLevel.WARN: ("Review the findings above. The policy has not blocked this PR."),
}


def _format_verdict_markdown(verdict: Verdict | None) -> list[str]:
    if verdict is None:
        return []

    label = _VERDICT_BANNER[verdict.level]
    lines = [f"## tokentoll verdict: {label}", ""]

    fails = [f for f in verdict.findings if f.severity == VerdictLevel.FAIL]
    warns = [f for f in verdict.findings if f.severity == VerdictLevel.WARN]

    if fails:
        lines.append(f"**Blocking findings ({len(fails)}):**")
        lines.append("")
        for f in fails:
            loc = (
                f"`{f.file_path}:{f.line_number}` - "
                if f.file_path and f.line_number is not None
                else ""
            )
            lines.append(f"- {loc}{f.message}")
        lines.append("")

    if warns:
        lines.append(f"**Warnings ({len(warns)}):**")
        lines.append("")
        for f in warns:
            loc = (
                f"`{f.file_path}:{f.line_number}` - "
                if f.file_path and f.line_number is not None
                else ""
            )
            lines.append(f"- {loc}{f.message}")
        lines.append("")

    if verdict.level == VerdictLevel.PASS and not fails and not warns:
        lines.append("All configured budgets and rules were satisfied.")
        lines.append("")

    action = _VERDICT_REQUIRED_ACTION.get(verdict.level)
    if action:
        lines.append(f"> {action}")
        lines.append("")

    lines.append("---")
    lines.append("")
    return lines


def _model_display(model: str | None, est: CostEstimate | None = None) -> str:
    if model:
        return model
    if est and est.used_default_model:
        return f"{est.used_default_model} (default)"
    return "<dynamic>"


def _fmt_cost(val: float | None) -> str:
    if val is None:
        return "N/A"
    if val < 0.01:
        return f"${val:.6f}"
    return f"${val:.2f}"


def _fmt_delta(val: float | None) -> str:
    if val is None:
        return "N/A"
    sign = "+" if val > 0 else ""
    if abs(val) < 0.01:
        return f"{sign}${val:.6f}"
    return f"{sign}${val:.2f}"


def format_scan_report_markdown(report: ScanReport) -> str:
    if not report.estimates:
        return "No LLM API calls detected."

    lines = [
        "## tokentoll Scan Report",
        "",
        "| File | Line | SDK | Model | Est. Cost/Call | Monthly |",
        "|------|------|-----|-------|---------------|---------|",
    ]

    for est in report.estimates:
        model = _model_display(est.call.model, est)
        cost = _fmt_cost(est.estimated_cost_per_call) if est.model_found else "N/A"
        monthly = _fmt_cost(est.monthly_estimate) if est.model_found else "N/A"
        lines.append(
            f"| `{est.call.file_path}` | {est.call.line_number} "
            f"| {est.call.sdk} | {model} | {cost} | {monthly} |"
        )

    lines.append("")
    lines.append(f"**Total estimated monthly cost: {_fmt_cost(report.total_monthly_estimate)}**")

    if report.assumptions:
        lines.append("")
        lines.append("<details>")
        lines.append("<summary>Assumptions</summary>")
        lines.append("")
        for a in report.assumptions:
            lines.append(f"- {a}")
        lines.append("")
        lines.append("</details>")

    lines.append("")
    lines.append("*Generated by [tokentoll](https://github.com/Jwrede/tokentoll)*")
    return "\n".join(lines)


def format_diff_report_markdown(report: DiffReport, verdict: Verdict | None = None) -> str:
    active_diffs = [d for d in report.call_diffs if d.change_type.value != "unchanged"]

    if not active_diffs:
        verdict_lines = _format_verdict_markdown(verdict)
        if verdict_lines:
            return "\n".join(verdict_lines) + "## tokentoll\n\nNo LLM API cost changes detected."
        return "## tokentoll\n\nNo LLM API cost changes detected."

    lines: list[str] = []
    lines.extend(_format_verdict_markdown(verdict))
    lines.extend(
        [
            "## tokentoll",
            "",
            "| | File | Line | SDK | Model | Est. Cost/Call | Monthly Delta |",
            "|---|------|------|-----|-------|---------------|---------------|",
        ]
    )

    icons = {
        "added": ":heavy_plus_sign:",
        "removed": ":heavy_minus_sign:",
        "modified": ":arrows_counterclockwise:",
    }

    for d in active_diffs:
        call = d.new_call or d.old_call
        if call is None:
            continue

        icon = icons.get(d.change_type.value, "")

        if d.change_type.value == "modified" and d.old_call and d.new_call:
            old_model = _model_display(d.old_call.model, d.old_estimate)
            new_model = _model_display(d.new_call.model, d.new_estimate)
            model_str = f"{old_model} -> {new_model}"
            cost_str = (
                f"{_fmt_cost(d.old_estimate.estimated_cost_per_call if d.old_estimate else None)}"
                f" -> "
                f"{_fmt_cost(d.new_estimate.estimated_cost_per_call if d.new_estimate else None)}"
            )
        else:
            est = d.new_estimate or d.old_estimate
            model_str = _model_display(call.model, est)
            cost_str = _fmt_cost(est.estimated_cost_per_call if est else None)

        delta_str = _fmt_delta(d.monthly_delta)

        lines.append(
            f"| {icon} | `{call.file_path}` | {call.line_number} "
            f"| {call.sdk} | {model_str} | {cost_str} | {delta_str} |"
        )

    lines.append("")
    lines.append(
        f"**Monthly cost impact: {_fmt_delta(report.total_monthly_delta)}/mo** "
        f"(assuming {report.assumptions[0] if report.assumptions else '?'})"
    )

    lines.append("")
    lines.append("<details>")
    lines.append("<summary>Assumptions and methodology</summary>")
    lines.append("")
    lines.append(
        "- Input tokens estimated at 500 where prompt content is not statically analyzable"
    )
    lines.append("- Output tokens from max_tokens parameter or model default")
    lines.append("- Pricing data sourced from LiteLLM")
    lines.append("- Static estimate -- actual costs depend on runtime call volume and prompt sizes")
    lines.append("")
    lines.append("</details>")

    lines.append("")
    lines.append("*Generated by [tokentoll](https://github.com/Jwrede/tokentoll)*")

    return "\n".join(lines)
